
package com.pixeldroid.r_c4d3.controls
{

	/**
	Provides human readable labels for keys that can be looked up by keycode.
	*/
	public class KeyLabels {
		
		
		private static const UNDEFINED:String = "unknown key";
		private static const LABELS:Array = [
			UNDEFINED, /* 0 */
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"BACKSPACE",
			"TAB",
			UNDEFINED,
			UNDEFINED,
			"CENTER",
			"ENTER",
			UNDEFINED,
			UNDEFINED,
			"SHIFT",
			"CONTROL/APPLE",
			UNDEFINED,
			"PAUSE",
			"CAPS LOCK",
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"ESCAPE",
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"SPACE", /* 32 */
			"PAGE UP",
			"PAGE DOWN",
			"END",
			"HOME",
			"ARROW LEFT",
			"ARROW UP",
			"ARROW RIGHT",
			"ARROW DOWN",
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"INSERT",
			"DELETE",
			UNDEFINED,
			"NUMBER 0",
			"NUMBER 1",
			"NUMBER 2",
			"NUMBER 3",
			"NUMBER 4",
			"NUMBER 5",
			"NUMBER 6",
			"NUMBER 7",
			"NUMBER 8",
			"NUMBER 9",
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"LETTER A", /* 65 */
			"LETTER B",
			"LETTER C",
			"LETTER D",
			"LETTER E",
			"LETTER F",
			"LETTER G",
			"LETTER H",
			"LETTER I",
			"LETTER J",
			"LETTER K",
			"LETTER L",
			"LETTER M",
			"LETTER N",
			"LETTER O",
			"LETTER P",
			"LETTER Q",
			"LETTER R",
			"LETTER S",
			"LETTER T",
			"LETTER U",
			"LETTER V",
			"LETTER W",
			"LETTER X",
			"LETTER Y",
			"LETTER Z",
			"START MENU LEFT",
			"START MENU RIGHT",
			"CONTEXT MENU",
			UNDEFINED,
			UNDEFINED,
			"NUMPAD 0", /* 96 */
			"NUMPAD 1",
			"NUMPAD 2",
			"NUMPAD 3",
			"NUMPAD 4",
			"NUMPAD 5",
			"NUMPAD 6",
			"NUMPAD 7",
			"NUMPAD 8",
			"NUMPAD 9",
			"NUMPAD MULTIPLY",
			"NUMPAD PLUS",
			UNDEFINED,
			"NUMPAD MINUS",
			"NUMPAD PERIOD",
			"NUMPAD DIVIDE",
			"F1", /* 112 */
			"F2",
			"F3",
			"F4",
			"F5",
			"F6",
			"F7",
			"F8",
			"F9",
			"F10",
			"F11",
			"F12",
			"F12",
			UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"NUMLOCK", /* 144 */
			"SCROLL LOCK",
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			UNDEFINED,
			"SEMICOLON", /* 186 */
			"EQUAL SIGN",
			"COMMA",
			"HYPHEN",
			"PERIOD",
			"FORWARD SLASH",
			"BACK TICK",
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED, UNDEFINED,
			UNDEFINED, 
			UNDEFINED, 
			"LEFT BRACE", /* 219 */
			"BACK SLASH",
			"RIGHT BRACE",
			"SINGLE QUOTE"
		];
		
		/**
		Get a human readable label for the key with the assigned <code>keyCode</code>.
		@param keyCode number assigned to keyboard key by flash,
		probably obtained from <code>KeyboardEvent.keyCode</code>
		@return string label describing key represented by keyCode
		*/
		public static function getLabel(keyCode:uint):String 
		{
			return (keyCode < LABELS.length) ? LABELS[int(keyCode)] : UNDEFINED;
		}
		
	}
	
}
